version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  AfterInstall:
    - location: setup.sh
      timeout: 100
  ApplicationStart:
    - location: deploy.sh
      timeout: 100