version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_NAME .
  post_build:
    commands:
      - echo Tagging the Docker image...
      - docker tag $IMAGE_NAME $DOCKER_USERNAME/$IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Pushing the Docker image to Docker Hub...
      - docker push $DOCKER_USERNAME/$IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Docker image pushed successfully to Docker Hub
