version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t devopswithashok/codedeploy-ecs .
      - docker push devopswithashok/codedeploy-ecs
  # post_build:
  #   commands:
  #     - echo Push to Docker Hub
  #     - echo Pushing the Docker image to Docker Hub...
  #     - docker push devopswithashok/codedeploy-ecs
